Fix compile error for Android/Linux - undefined symbol: nghttp3_ntohl
Summary:
Fix compile error for Android/Linux - undefined symbol: nghttp3_ntohl

Summary:
Found the following compile error when we build the latest nghttp3 for
Android/Linux.

```
ld.lld: error: undefined symbol: nghttp3_ntohl >>> referenced by nghttp3_conv.c:58 (third-party/nghttp3/lib/nghttp3_conv.c:58) >>> ../nghttp3#compile-pic-nghttp3_conv.c.o2a37e81d,platform010-clang/lib/nghttp3_conv.c.o:(nghttp3_get_varint)
```

nghttp3_ntohl is not a function or macro. We should use ntohl instead
which is also part of previos logic in #135.

Test Plan:
Compile and check no error.

Reviewers:

Subscribers:

Tasks:

Tags: